# https://www.appveyor.com/docs/appveyor-yml/
#---------------------------------#
#      general configuration      #
#---------------------------------#
# version format
version: '0.2.0.{build}'      

# including commits in the following folders only
only_commits:
  files:
    - src\
    - test\

# update csproj properties
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

#---------------------------------#
#    environment configuration    #
#---------------------------------#
# Build worker image (VM template)
image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#
# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
- cmd: set ASPNETCORE_ENVIRONMENT=LocalDevelopment
- cmd: dotnet restore

build:
  # enable MSBuild parallel builds
  parallel: true   
  # path to Visual Studio solution or project               
  project: FeatureBits.sln      
  # MSBuild verbosity level
  verbosity: minimal

after_build:
- cmd: dotnet pack ".\src\FeatureBits.Core\FeatureBits.Core.csproj" /p:Configuration=Release --no-build
- cmd: dotnet pack ".\src\FeatureBits.Data\FeatureBits.Data.csproj" /p:Configuration=Release --no-build
- cmd: dotnet pack ".\src\FeatureBits.Console\FeatureBits.Console.csproj" /p:Configuration=Release --no-build

#---------------------------------#
#       tests configuration       #
#---------------------------------#
# auto discovery

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  provider: NuGet  
  api_key:
    secure: wojT8rmz0nIA91iw6Xa3cjtG/Virxzqbv7eeM32eBzl0LeUbDzL8Quv++l9p27rg
  skip_symbols: true  
  artifact: /.*\.nupkg/
  on:
    branch: master


